name = "report-problem-parser"
main = "src/index.ts"
compatibility_date = "2024-09-05"

[env.production]
name = "report-problem-parser"
custom_domains = ["complaints.aso.market"]

[env.staging]
name = "report-problem-parser-staging"
